name: "podevent"              # REQUIRED: the plug-in command name, to be invoked under 'kubectl'
shortDesc: "Plugin for showing pods' event" # REQUIRED: the command short description, for help
longDesc: ""                      # the command long description, for help
example: ""                       # command example(s), for help
command: "./podevent.sh"        # REQUIRED: the command, binary, or script to invoke when running the plug-in
#flags:                            # flags supported by the plug-in
#  - name: "flag-name"             # REQUIRED for each flag: flag name
#    shorthand: "f"                # short version of the flag name
#    desc: "example flag"          # REQUIRED for each flag: flag description
#    defValue: "extreme"           # default value of the flag
